services:
  - type: web
    name: picture-qr-backend
    env: node
    plan: free
    buildCommand: backend/ && npm install
    startCommand: backend/ && npm start
    rootDir: backend/


  - type: web
    name: your-app
    env: node
    buildCommand: |
      ./init_db.sh
      npm install
    startCommand: node backend/server.js

